import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the complete portfolio case openings", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>YONG QI — Portfolio 2026<\/title>/i);
  assert.match(html, /耳机详情视觉/);
  assert.match(html, /卫浴详情视觉/);
  assert.equal((html.match(/详情视觉设计/g) ?? []).length, 2);
  assert.doesNotMatch(html, /耳机电商详情视觉|卫浴产品电商视觉/);
  assert.match(html, /皮卡防滚架视觉/);
  assert.match(html, /sticker-crossborder\.png/);
  assert.match(html, /aria-label="向下滚动查看案例"/);
  assert.match(html, /电商视觉 · 三维渲染 · AI 图像/);
  assert.doesNotMatch(html, /产品视觉 · 三维渲染 · AI 图像/);
  assert.match(html, /carousel-sticker-arrow/);
  assert.match(html, /footer-sticker-arrow/);
  assert.match(html, /皮卡防滚架跨境电商视觉/);
  assert.match(html, /350 LBS 承重、防锈耐候、车型适配与载物拓展/);
  assert.match(html, /以户外度假旅行为视觉主线，通过海岸场景强化产品的户外使用属性/);
  assert.doesNotMatch(html, /以户外越野实景、硬朗低饱和色调与结构特写/);
  assert.match(html, /TRUCK ROLL BAR/);
  assert.match(html, /视觉方向 · 场景合成/);
  assert.doesNotMatch(html, /卖点策划/);
  assert.match(html, /Blender · Photoshop · AI 辅助/);
  assert.match(html, /\/v2\/crossborder\/truck-roll-bar\/a-plus\.jpg/);
  assert.match(html, /\/v2\/crossborder\/truck-roll-bar\/strategy-hero\.jpg/);
  assert.match(html, /data-preload-src="\/preview\/v2\/crossborder\/truck-roll-bar\/strategy-hero\.webp"/);
  assert.match(html, /data-full-src="\/v2\/crossborder\/truck-roll-bar\/strategy-hero\.jpg"/);
  assert.match(html, /poster="\/portfolio-ufo-cover\.jpg"/);
  assert.match(html, /class="hero-title-art"/);
  assert.match(html, /class="hero-title-float"/);
  assert.match(html, /class="hero-title-shine"/);
  assert.match(html, /mask="url\(#hero-title-alpha\)"/);
  assert.match(html, /viewBox="45 275 1368 510"/);
  assert.match(html, /href="\/portfolio-title\.png"/);
  assert.match(html, /class="hero-title-float inside-title-float"/);
  assert.match(html, /class="hero-title-art inside-title-art"/);
  assert.match(html, /viewBox="29 282 1203 640"/);
  assert.match(html, /href="\/inside-title\.png"/);
  assert.match(html, /mask="url\(#inside-title-alpha\)"/);
  assert.doesNotMatch(html, /<h1><span>PORT<\/span><span>FOLIO<\/span><\/h1>/);
  assert.match(html, /class="site-loader /);
  assert.match(html, /role="progressbar"/);
  assert.match(html, /产品渲染/);
  assert.match(html, /AIGC工作流/);
  assert.match(html, /提示词设计 · 图像合成 · 局部重绘 · 统一调色/);
  assert.match(html, /产品基底 · 场景搭建 · 光影融合 · 成片输出/);
  assert.doesNotMatch(html, /生成 · 合成 · 局部修正 · 精修/);
  assert.doesNotMatch(html, /产品基底 · 场景生成 · 细节修正 · 后期/);
  assert.match(html, /\/illustrations\/sticker-ssww-bath\.png/);
  assert.match(html, /\/illustrations\/sticker-product-knight\.png/);
  assert.equal((html.match(/data-preload-src="\/preview\/illustrations\/sticker-aigc-office\.webp"/g) ?? []).length, 2);
  assert.equal((html.match(/data-full-src="\/illustrations\/sticker-aigc-office\.png"/g) ?? []).length, 2);
  assert.doesNotMatch(html, /\/illustrations\/ufo-earbud\.webp/);
  assert.equal((html.match(/class="strategy-textures"/g) ?? []).length, 2);
  assert.doesNotMatch(html, /strategy-ufo-beam/);
  assert.match(html, /Better Call <span>Zhou<\/span>/);
  assert.match(html, /<h3>产品场景生成<\/h3>/);
  assert.doesNotMatch(html, /<h3>活动视觉<\/h3>/);
  assert.doesNotMatch(html, /Campaign Posters &amp; Layout Studies/);
  assert.match(html, /<h3>独立浴缸<\/h3>/);
  assert.match(html, /Freestanding Bath/);
  for (const image of [7, 8, 9, 10]) assert.match(html, new RegExp(`/v2/ssww/${String(image).padStart(2, "0")}\\.webp`));
  assert.doesNotMatch(html, /沙发产品 AI 短片/);
  assert.doesNotMatch(html, /green-lounge-silent\.mp4/);
  assert.doesNotMatch(html, /AI PRODUCT FILM/);
  assert.equal((html.match(/class="ai-process-item is-(?:landscape|portrait)/g) ?? []).length, 12);
  assert.equal((html.match(/class="ai-process-board"/g) ?? []).length, 1);
  assert.match(html, /AIGC VISUAL SHOWCASE · 视觉作品展示/);
  assert.equal((html.match(/class="aigc-showcase-divider reveal"/g) ?? []).length, 1);
  assert.match(html, /CHARACTER CONSISTENCY · 人物一致性/);
  assert.equal((html.match(/class="aigc-consistency-label reveal"/g) ?? []).length, 1);
  assert.equal((html.match(/class="ai-process-vehicle-group"/g) ?? []).length, 2);
  assert.match(html, /产品场景生成流程/);
  assert.match(html, /红色越野车/);
  assert.match(html, /蓝色皮卡/);
  assert.match(html, /户外风扇/);
  assert.match(html, /沙发场景/);
  assert.match(html, /沙发场景 · 渲染/);
  assert.equal((html.match(/<h5>渲染<\/h5>/g) ?? []).length, 4);
  assert.equal((html.match(/<h5>生成<\/h5>/g) ?? []).length, 3);
  assert.equal((html.match(/<h5>模特<\/h5>/g) ?? []).length, 1);
  assert.equal((html.match(/<h5>精修<\/h5>/g) ?? []).length, 4);
  assert.doesNotMatch(html, /汽车前杠/);
  assert.doesNotMatch(html, /手持风扇/);
  assert.doesNotMatch(html, /PROCESS SET/);
  assert.match(html, /\/v2\/aigc-process\/set-02\/03\.webp/);
  assert.match(html, /\/v2\/aigc-process\/set-03\/03\.jpg/);
  assert.match(html, /单品渲染/);
  assert.doesNotMatch(html, /<h3>机械腕表<\/h3>/);
  assert.match(html, /\/v2\/renders\/watch\/detail-01\.webp/);
  assert.match(html, /\/v2\/renders\/watch\/detail-02\.webp/);
  assert.match(html, /4 个系列 · 24 幅作品/);
  assert.match(html, /CATEGORY \/ 展示类型/);
  assert.match(html, /单品产品渲染/);
  assert.match(html, /FOCUS \/ 视觉重点/);
  assert.match(html, /材质 · 灯光 · 构图 · 氛围/);
  assert.match(html, /COLLECTION \/ 收录内容/);
  assert.match(html, /TOOLS \/ 制作工具/);
  assert.doesNotMatch(html, /跨品类产品渲染选集/);
  assert.doesNotMatch(html, /概念场景/);
  assert.doesNotMatch(html, /CONCEPT SCENE/);
  assert.match(html, /日化品渲染/);
  assert.match(html, /产品建模白模展示/);
  assert.match(html, /SOFTWARE · Blender · Plasticity/);
  assert.doesNotMatch(html, /白模与建模研究/);
  assert.match(html, /\/v2\/renders\/daily-care\/perfume-motion\.gif/);
  assert.match(html, /家居渲染/);
  assert.doesNotMatch(html, /\/v2\/renders\/18\.webp/);
  assert.doesNotMatch(html, /\/v2\/renders\/23\.webp/);
  assert.doesNotMatch(html, /\/v2\/renders\/11\.webp/);
  assert.doesNotMatch(html, /\/v2\/renders\/13\.webp/);
  assert.doesNotMatch(html, /\/v2\/renders\/14\.webp/);
  assert.doesNotMatch(html, /\/v2\/renders\/17\.webp/);
  assert.doesNotMatch(html, /\/v2\/renders\/16\.webp/);
  assert.doesNotMatch(html, /\/v2\/renders\/20\.webp/);
  assert.doesNotMatch(html, /\/v2\/renders\/22\.webp/);
  assert.doesNotMatch(html, /\/v2\/renders\/29\.webp/);
  assert.doesNotMatch(html, /\/v2\/renders\/25\.webp/);
  assert.doesNotMatch(html, /\/v2\/renders\/28\.webp/);
  assert.match(html, /\/v2\/renders\/21\.webp/);
  assert.match(html, /\/v2\/renders\/30\.webp/);
  assert.match(html, /\/v2\/renders\/home\/green-sofa\.webp/);
  assert.equal((html.match(/<header class="project-opening project-opening-/g) ?? []).length, 5);
  assert.equal((html.match(/class="project-opening-facts"/g) ?? []).length, 5);
  assert.match(html, /<svg class="heading-spots" viewBox="0 0 480 160" preserveAspectRatio="xMidYMid meet"/);
  assert.doesNotMatch(html, /class="split-intro/);
});

test("keeps the editorial opening system shared and ratio-safe", async () => {
  const [page, css, layout] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
  ]);

  assert.match(page, /function ProjectOpening/);
  assert.match(page, /function HeadingSpots/);
  assert.match(page, /function AiImageProcess/);
  assert.match(page, /title="AIGC工作流"/);
  assert.match(page, /subtitle="AIGC Workflow"/);
  assert.doesNotMatch(page, /AI IMAGE WORKFLOW · 12 STEPS/);
  assert.match(page, /DIRECTION \/ 探索方向/);
  assert.match(page, /FOCUS \/ 探索重点/);
  assert.match(page, /METHOD \/ 实践方式/);
  assert.match(page, /WORKFLOW \/ 工作流程/);
  assert.match(page, /function updateImageTilt/);
  assert.match(page, /function beginImageTilt/);
  assert.match(page, /activeImageTiltSession/);
  assert.match(page, /video\.addEventListener\("canplay", resume\)/);
  assert.match(page, /const playbackGuard = window\.setInterval\(keepPlaying, 1200\)/);
  assert.match(page, /video\.setAttribute\("webkit-playsinline", ""\)/);
  assert.match(page, /const bounds = element\.getBoundingClientRect\(\)/);
  assert.match(page, /window\.addEventListener\("pointermove", track, \{ passive: true \}\)/);
  assert.doesNotMatch(page, /onPointerLeave=\{resetImageTilt\}/);
  assert.match(page, /function updateStickerTilt/);
  assert.match(page, /classList\.add\("is-visible"\)/);
  assert.match(page, /observer\.unobserve\(entry\.target\)/);
  assert.doesNotMatch(page, /classList\.toggle\("is-visible", entry\.isIntersecting\)/);
  assert.match(page, /rootMargin: "0px 0px -6% 0px"/);
  assert.match(page, /function resetStickerTilt/);
  assert.match(page, /querySelectorAll<HTMLElement>\("\.project-opening-artwork\.is-sticker-artwork"\)/);
  assert.match(page, /window\.requestAnimationFrame\(render\)/);
  assert.match(page, /window\.addEventListener\("pointermove", track/);
  assert.equal((page.match(/onPointerEnter=\{beginImageTilt\}/g) ?? []).length, 2);
  assert.equal((page.match(/onPointerMove=\{updateImageTilt\}/g) ?? []).length, 2);
  assert.match(page, /className="zoom-image-tilt-frame"/);
  assert.match(page, /--tilt-x/);
  assert.match(page, /--tilt-move-x/);
  assert.equal((page.match(/<ProjectOpening index=/g) ?? []).length, 5);
  assert.doesNotMatch(page, /function ProjectHeading/);
  assert.doesNotMatch(page, /render-heading-spots/);
  assert.equal((page.match(/className="strategy-textures"/g) ?? []).length, 2);
  assert.doesNotMatch(page, /strategy-ufo-beam/);
  assert.doesNotMatch(page, /system-doodle/);
  assert.match(css, /\.heading-spots\{[^}]*aspect-ratio:3\/1/);
  assert.match(css, /\.ai-process-grid\{[^}]*grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);
  assert.match(css, /\.ai-process-image\{[^}]*aspect-ratio:4\/3/);
  assert.match(css, /\.ai-process-item\.is-portrait \.ai-process-image\{aspect-ratio:3\/4/);
  assert.match(css, /\.ai-process-vehicle-row\{[^}]*grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
  assert.match(css, /\.ai-process-feature-grid\{[^}]*grid-template-columns:minmax\(0,\.75fr\) minmax\(0,1\.25fr\)/);
  assert.match(css, /\.ai-process-feature-item:nth-child\(3\)\{[^}]*grid-column:2[^}]*grid-row:1\/span 2/);
  assert.match(css, /\.ai-process-secondary-row>\.ai-process-secondary-product\+\.ai-process-secondary-product\{[^}]*margin-top:0[^}]*padding-top:0[^}]*border-top:0/);
  assert.match(css, /\.ai-process-secondary-feature-grid\{[^}]*grid-template-columns:minmax\(0,1\.15fr\) minmax\(0,\.85fr\)[^}]*aspect-ratio:1\.45\/1/);
  assert.match(css, /\.project-opening-artwork\.is-sticker-artwork \.responsive-picture\{[^}]*overflow:visible/);
  assert.match(css, /\.project-opening-artwork\.is-crossborder-sticker\{[^}]*--sticker-scale:1\.3/);
  assert.match(css, /\.group-label>span,\.ai-process-product-title>span\{[^}]*border:2px solid #f2eee5[^}]*background:#171716/);
  assert.match(css, /\.directory-head>\.eyebrow,\.project-opening-topline>span:first-child,[^\{]+\{[^}]*border:2px solid #f2eee5[^}]*background:#171716/);
  assert.match(css, /main \.case-section \.zoom-image\.reveal\.is-visible:hover,[\s\S]*?transform:none/);
  assert.match(css, /main \.case-section \.zoom-image\.reveal\.is-visible>\.zoom-image-tilt-frame\{[^}]*pointer-events:none[^}]*rotateX\(var\(--tilt-x\)\)[^}]*rotateY\(var\(--tilt-y\)\)/);
  assert.match(css, /main \.case-section \.zoom-image-tilt-frame:before\{[^}]*opacity:0/);
  assert.match(css, /main \.case-section \.zoom-image\.is-pointer-tilting \.zoom-image-tilt-frame:before\{[^}]*opacity:1/);
  assert.match(css, /\.crossborder-strategy-strip\{[^}]*gap:clamp\(14px,1\.5vw,24px\)[^}]*border:0/);
  assert.match(css, /\.crossborder-strategy-strip>figure,\.crossborder-strategy-copy\{[^}]*border:0[^}]*border-radius:clamp\(12px,1\.1vw,20px\)/);
  assert.match(css, /\.crossborder-strategy-copy>header>span\{[^}]*background:#5b6a5e/);
  assert.match(css, /\.project-opening-facts\{/);
  assert.match(css, /@media\(max-width:560px\)\{[^]*\.project-opening-facts>div,[^]*grid-template-rows:8px minmax\(0,1fr\)[^]*font-size:clamp\(5px,1\.42vw,5\.8px\)/);
  assert.match(css, /\.crossborder-square-grid\{[^}]*grid-template-rows:repeat\(3,minmax\(0,1fr\)\)[^}]*align-content:stretch/);
  assert.match(css, /\.crossborder-square-grid \.zoom-image\{[^}]*height:100%[^}]*aspect-ratio:auto/);
  assert.match(css, /\.hero-editorial\{[^}]*grid-template-columns:1fr[^}]*grid-template-rows:minmax\(160px,\.6fr\) minmax\(330px,1\.4fr\)/);
  assert.match(css, /\.hero-editorial \.hero-art video\{[^}]*top:6%[^}]*height:88%[^}]*transform:none[^}]*object-fit:cover[^}]*object-position:68% 50%/);
  assert.match(css, /\.case-carousel-stage\{height:clamp\(274px,72vw,312px\)\}/);
  assert.match(css, /\.carousel-card\.case-aure,[^]*\.carousel-card\.case-ssww\{[^}]*height:100%[^}]*min-height:0[^}]*max-height:100%/);
  assert.match(css, /\.carousel-card \.tile-art\{transform:none\}/);
  assert.match(css, /\.carousel-card \.tile-art img\{[^}]*width:100%[^}]*height:100%[^}]*transform:none[^}]*object-fit:cover[^}]*object-position:center/);
  assert.match(css, /\.carousel-card \.tile-label\{padding-right:0\}/);
  assert.match(css, /\.carousel-card \.tile-label h3\{[^}]*max-width:100%[^}]*font-size:clamp\(15px,4\.7vw,19px\)/);
  assert.doesNotMatch(page, /function Arrow\(\)/);
  assert.doesNotMatch(page, /<Arrow \/>/);
  assert.match(css, /\.aure-title-block>p\{[^}]*margin:clamp\(8px,\.75vw,12px\) 0 clamp\(22px,1\.45vw,28px\)/);
  assert.match(css, /\.crossborder-strategy-copy>header>span\{[^}]*margin:clamp\(7px,\.6vw,10px\) 0 clamp\(14px,1vw,18px\)/);
  assert.match(css, /\.project-opening-artwork\.is-sticker-artwork/);
  assert.match(css, /--sticker-shadow-x/);
  assert.match(css, /--sticker-glint-x/);
  assert.doesNotMatch(css, /--sticker-glint-angle/);
  assert.match(css, /mask-image:var\(--sticker-image\)/);
  assert.match(css, /\.project-opening-artwork\.is-sticker-artwork::after\{[^}]*radial-gradient/);
  assert.doesNotMatch(css, /\.project-opening-artwork\.is-sticker-artwork::before\{/);
  assert.match(css, /\.ai-process-product-title\{/);
  assert.match(css, /\.about-contact-section \.about-contact-signature/);
  assert.match(css, /\.about-contact-section \.about-contact-signature\{[^}]*white-space:nowrap/);
  assert.match(css, /\.about-contact-main\{grid-template-columns:minmax\(0,1fr\)/);
  assert.match(css, /\.about-contact-main \.about-contact-copy\{[^}]*justify-self:end/);
  assert.doesNotMatch(css, /\.ai-process-puzzle\{/);
  assert.doesNotMatch(css, /\.ai-process-board\.is-portrait/);
  assert.match(css, /\.ai-process-board\{[^}]*width:100%[^}]*max-width:none[^}]*margin-bottom:clamp\(38px,4vw,58px\)/);
  assert.match(css, /\.aigc-showcase-divider\{[^}]*width:100%[^}]*border-top:1px solid rgba\(25,25,22,\.24\)/);
  assert.match(css, /\.aigc-showcase-divider>span\{[^}]*background:#171716[^}]*color:#f2eee5/);
  assert.match(css, /\.aigc-consistency-label\{[^}]*grid-column:1\/-1[^}]*width:100%/);
  assert.match(css, /\.aigc-consistency-label>span\{[^}]*border:1px solid #171716[^}]*border-radius:999px/);
  assert.match(css, /\.layout-product-study \.zoom-image:nth-child\(n\+4\)\{[^}]*grid-column:span 4;aspect-ratio:4\/3/);
  assert.match(page, /className="render-mosaic layout-home home-bento-grid"/);
  assert.match(page, /images: \[9, 10, \{ src: "\/v2\/renders\/home\/green-sofa\.webp"[^}]+\}, 21, 19, 27, 24, 30\], layout: "home"/);
  assert.doesNotMatch(page, /home-render-row/);
  assert.match(css, /\.render-mosaic\.layout-home\{[^}]*grid-template-columns:repeat\(4,minmax\(0,1fr\)\)[^}]*grid-auto-rows:clamp\(180px,26\.5cqw,390px\)/);
  assert.match(css, /\.render-mosaic\.layout-home>\.zoom-image:nth-child\(1\)\{[^}]*grid-column:1\/span 2[^}]*grid-row:1\/span 2/);
  assert.match(css, /\.render-mosaic\.layout-home>\.zoom-image:nth-child\(5\)\{[^}]*grid-column:3\/span 2[^}]*grid-row:3\/span 2/);
  assert.match(css, /\.render-mosaic\.layout-home>\.zoom-image:nth-child\(8\)\{[^}]*grid-column:2[^}]*grid-row:4/);
  assert.match(css, /\.layout-model-study \.zoom-image\{[^}]*aspect-ratio:1!important/);
  assert.match(css, /\.model-group\{[^}]*width:min\(88vw,1500px\)/);
  assert.match(css, /\.model-software-badge\{[^}]*display:inline-flex[^}]*background:#171716[^}]*font-size:9px/);
  assert.match(css, /\.layout-model-study\{[^}]*grid-template-columns:repeat\(6,minmax\(0,1fr\)\)/);
  assert.doesNotMatch(page, /sofa-row-stack/);
  assert.doesNotMatch(page, /SofaWorkflow/);
  assert.doesNotMatch(page, /sofaPhases/);
  assert.match(css, /\.brand::before\{[^}]*linear-gradient/);
  assert.match(css, /@keyframes depth-media-arrive/);
  assert.match(css, /translate3d\(0,128px,-520px\)/);
  assert.match(css, /\.ai-product-mosaic \.zoom-image\.reveal\.is-visible\{[^}]*animation:depth-media-arrive/);
  assert.match(css, /\.aure-brand-strip:not\(\.ssww-brand-strip\)\{[^}]*grid-template-columns:minmax\(0,2\.1fr\) minmax\(280px,1fr\)/);
  assert.match(css, /\.aure-brand-strip:not\(\.ssww-brand-strip\) \.aure-product-cutout::after\{[^}]*width:44px[^}]*clip-path:inset\(0 0 0 50%\)/);
  assert.match(css, /\.ssww-brand-strip\{[^}]*grid-template-columns:minmax\(0,2\.1fr\) minmax\(280px,1fr\)/);
  assert.match(css, /\.ssww-brand-strip \.ssww-product-cutout::after\{[^}]*width:44px[^}]*clip-path:inset\(0 0 0 50%\)/);
  assert.match(css, /\.aure-case-intro,\.aure-case-intro\.ssww-case-intro\{height:clamp\(860px,55vw,900px\)/);
  assert.match(css, /\.ssww-case-intro \.ssww-hero-visual img\{object-position:50% 82%\}/);
  assert.doesNotMatch(css, /\.ai-process-piece:not\(:first-child\)::after/);
  assert.match(css, /main \.case-section \.zoom-image\.reveal\.is-visible\{[^}]*rotateX\(var\(--tilt-x\)\) rotateY\(var\(--tilt-y\)\)/);
  assert.match(css, /translate3d\(var\(--tilt-move-x\)/);
  assert.match(css, /\.carousel-card \.tile-art\{[^}]*var\(--tilt-move-x\)/);
  assert.match(css, /grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/);
  assert.match(css, /\.hero-editorial\{[^}]*height:100svh[^}]*grid-template-columns:minmax\(0,\.84fr\) minmax\(0,1\.16fr\)/);
  assert.match(css, /\.crossborder-showcase\{grid-template-columns:minmax\(0,2fr\) minmax\(80px,\.72fr\)/);
  assert.match(css, /\.project-opening-facts\{grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/);
  assert.match(css, /\.site-loader\{[^}]*position:fixed[^}]*z-index:9999/);
  assert.match(css, /\.hero-title-float\{[^}]*width:min\(100%,620px\)[^}]*animation:hero-title-float/);
  assert.match(css, /@keyframes hero-title-float\{[^}]*translateY\(0\)/);
  assert.match(css, /\.hero-title-art\.is-shining \.hero-title-shine\{opacity:\.82\}/);
  assert.match(css, /\.inside-title-float\{[^}]*width:min\(100%,329px\)/);
  assert.match(css, /\.responsive-picture\.directory-absurdity>img\{[^}]*height:auto[^}]*aspect-ratio:1000\/675[^}]*object-fit:contain/);
  assert.doesNotMatch(css, /hero-title-(?:art|float)[^\n{]*\{[^}]*rotate/);
  assert.match(page, /style\.setProperty\("--title-shine-x"/);
  assert.match(page, /const viewBox = title\.viewBox\.baseVal/);
  assert.match(page, /classList\.add\("is-shining"\)/);
  assert.match(css, /\.aure-case-intro,\.aure-case-intro\.ssww-case-intro\{[^}]*grid-template-columns:1fr[^}]*grid-template-rows:minmax\(170px,30%\) minmax\(0,70%\)/);
  assert.match(css, /\.crossborder-strategy-strip\{[^}]*grid-template-columns:1fr[^}]*grid-template-rows:minmax\(165px,31%\) minmax\(0,69%\)/);
  assert.match(page, /video\.volume = 0/);
  assert.match(page, /document\.querySelectorAll<HTMLPictureElement>\("picture"\)/);
  assert.match(page, /const entryContentRatio = 2 \/ 3/);
  assert.match(page, /entryBoundary = documentHeight \* entryContentRatio/);
  assert.match(page, /loaded === sources\.length/);
  assert.doesNotMatch(page, /safetyTimer|80% 页面预览已缓存|张预览|共 \$\{sources\.length\} 张/);
  assert.match(page, /preload="auto" poster="\/portfolio-ufo-cover\.jpg"/);
  assert.match(page, /source src="\/portfolio-cover-2026\.mp4" type="video\/mp4"/);
  assert.match(layout, /rel="preload" href="\/portfolio-ufo-cover\.jpg" as="image"/);
  assert.match(page, /data-preload-src=\{previewSrc\}/);
  assert.match(page, /data-full-src=\{src\}/);
  assert.match(page, /const isAnimated = \/\\\.gif/);
  assert.match(page, /isAnimated \|\| useOriginal \? src : previewSrc/);
  assert.match(page, /rootMargin: "1800px 0px"/);
  assert.match(page, /if \(!useOriginal\)/);
  assert.match(page, /window\.matchMedia\("\(max-width: 900px\)"\)\.matches \? 3 : 6/);
  assert.match(page, /正在加载高清原图/);
  assert.match(page, /retryAsset\(modal\.src, modalRetry\)/);
  assert.match(css, /:root\{color-scheme:only light\}/);
  assert.match(css, /\.site-preparing\{height:auto;overflow:visible\}/);
  assert.match(css, /\.aure-brand-strip \.aure-product-cutout::before,\.aure-brand-strip \.aure-product-cutout::after\{display:none!important\}/);
  assert.match(css, /\.hero-editorial \.hero-art video\{left:0;top:50%;inset:auto;width:100%;height:auto/);
  assert.match(page, /title: "跨境电商设计"[^\n]*amazon-auto-parts-card\.jpg/);
  assert.match(css, /\.carousel-card \.tile-label h3\s*\{[^}]*letter-spacing: \.04em/);
  assert.match(css, /\.carousel-card\.case-crossborder \.tile-art img\s*\{[^}]*transform: scale\(1\.32\)[^}]*transform-origin: 50% 68%/);
  assert.match(layout, /colorScheme: "light"/);
  assert.match(layout, /YONG QI — Portfolio 2026/);
});
